{
 "title": "04_dashboard_with_data_links",
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   { "name": "time_period", "label": "Time Period", "query": "day,week,month" },
   { "name": "moving_average_periods", "label": "Periods in Moving Average", "query": "7" },
   {
    "name": "community_page_title",
    "query": "How to Rename Values in Grafana Using Regex-Based Value Mapping - Grafana / How To - Grafana Labs Community Forums"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div\n    style=\"\n        background-image: url(https://grafana.com/static/img/grafana_labs.jpg);\n        background-position: 0% 25%;\n        background-size: cover;\n        text-align: right;\n    \"\n>\n    <img \n        style=\"\n            height:2em;\n            margin:0.5%;\n            padding-right: 2em;\n        \"\n        src=\"https://grafana.com/static/assets/internal/grafana_logo-web.svg\"\n    >\n</div>\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 2 },
   "options": {
    "content": "# Step 4: Data Links!\n\nDesign elements borrowed **heavily** from a similar [post](https://grafana.com/blog/2022/05/31/grafana-for-business-intelligence-how-grafana-labs-uses-dashboards-for-more-than-observability-data/) I wrote on using Grafana for BI"
   }
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 6 },
   "options": {
    "content": "<div style=\"vertical-align: top; border: 0px;\"\">\n    <p style=\"text-align: center; font-size: 150%; padding: 0px; margin: 0px;\">\n        <b>Overview</b>\n    </p>\n    <p style=\"text-align: center; font-size: 80%; padding: 0px; margin: 0px\">\n        <em>(does NOT update based on top time selection)</em>\n    </p> \n</div>"
   }
  },
  {
   "title": "Average Data by ${time_period}",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "panelId": 11 }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Grafana Community Page Views",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "with\n\npage_views as (\n\n    select\n        date_trunc('${time_period}', p.received_date) as time_period\n        ,sum(page_views) as page_views\n        ,sum(new_page_views) as new_page_views\n        ,sum(unique_visitors) as unique_visitors\n        ,sum(unique_pages) as unique_pages\n    from\n        rpt_community_stats_daily p\n    group by 1\n\n),\n\nfinal as (\n\n    select\n        p.time_period\n        ,p.page_views\n        ,p.new_page_views\n        ,p.unique_visitors\n        ,p.unique_pages\n        ,avg(p.page_views) over (order by p.time_period rows between (${moving_average_periods}-1) preceding and current row) as moving_average\n    from\n        page_views p\n\n)\n\nselect *\nfrom final\nwhere $__timeFilter(time_period)\norder by 1\n"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 25 }, "options": { "content": "---" } },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 28 },
   "options": {
    "content": "<div style=\"vertical-align: top; border: 0px;\"\">\n    <p style=\"text-align: center; font-size: 150%; padding: 0px; margin: 0px;\">\n        <b>Community Forum Viewership by Page</b>\n    </p>\n    <p style=\"text-align: center; font-size: 80%; padding: 0px; margin: 0px\">\n        <em>(does NOT update based on top time selection)</em>\n    </p> \n</div>"
   }
  },
  {
   "title": "Page Views by ${time_period}: ${community_page_title}",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "with\n\npage_views as (\n\n    select\n        date_trunc('${time_period}', p.received_date) as time_period\n        ,sum(page_views) as page_views\n    from\n        rpt_community_page_stats_daily p\n    where\n        p.page_title = cast('${community_page_title}' as String)\n    group by 1\n\n),\n\nfinal as (\n\n    select\n        p.time_period\n        ,p.page_views\n        ,avg(p.page_views) over (order by p.time_period rows between (${moving_average_periods}-1) preceding and current row) as moving_average\n    from\n        page_views p\n\n)\n\nselect *\nfrom final\nwhere $__timeFilter(time_period)\norder by 1\n"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Top 20 Pages by Total Page Views",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "with\n\npage_views as (\n\n    select\n        p.page_title\n        ,p.page_path\n        ,sum(page_views) as page_views\n        ,sum(unique_visitors) as unique_visitors\n    from\n        rpt_community_page_stats_daily p\n    where\n        $__timeFilter(received_date)\n    group by 1,2\n\n),\n\nfinal as (\n\n    select\n        p.page_title\n        ,p.page_path\n        ,p.page_views\n        ,p.unique_visitors\n    from\n        page_views p\n\n)\n\nselect *\nfrom final\norder by 3 desc\nlimit 20"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 57 }, "options": { "content": "---" } },
  { "title": "Appendix", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  { "title": "Related Dashboards", "type": "dashlist", "gridPos": { "h": 9, "w": 24, "x": 0, "y": 60 } }
 ]
}