{
 "title": "05_community_overview",
 "time": { "from": "now-1y", "to": "now" },
 "templating": {
  "list": [
   { "name": "time_period", "label": "Time Period", "query": "day,week,month" },
   {
    "name": "moving_average_periods",
    "label": "Periods in Moving Average",
    "query": "1,2,3,4,5,6,7,8,9,10,11,12,13,14"
   },
   {
    "name": "community_page_title",
    "query": "Login issue after update to 10.1.0 (coming from 10.0.3) - Grafana / Authentication - Grafana Labs Community Forums"
   },
   {
    "name": "monthly_group_by",
    "query": "new_vs_existing,top_100_vs_others"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div\n    style=\"\n        background-image: url(https://grafana.com/static/img/grafana_labs.jpg);\n        background-position: 0% 25%;\n        background-size: cover;\n        text-align: right;\n    \"\n>\n    <img \n        style=\"\n            height:2em;\n            margin:0.5%;\n            padding-right: 2em;\n        \"\n        src=\"https://grafana.com/static/assets/internal/grafana_logo-web.svg\"\n    >\n</div>\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 2 },
   "options": {
    "content": "<p \n  style=\"font-size:350%;text-align:center; font-weight:normal;color:#cBD0200;>\"\n>\nOverall Engagement (Page Views, Unique Visitors)\n</p>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 5 },
   "options": {
    "content": "<p \n  style=\"font-size:150%;text-align:center; font-weight:normal;color:#cBD0200;>\"\n>\n💡 Key Question 💡 - At a high-level, how has our <span style=\"color: rgb(255, 248, 153)\">community engagement</span>  grown over time, and are there any general trends?\n</p>\n"
   }
  },
  {
   "title": "Average Data by ${time_period}",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "panelId": 11 }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Grafana Community Page Views",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "with\n\npage_views as (\n\n    select\n        date_trunc('${time_period}', p.received_date) as time_period\n        ,sum(page_views) as page_views\n        ,sum(new_page_views) as new_page_views\n        ,sum(unique_visitors) as unique_visitors\n        ,sum(unique_pages) as unique_pages\n    from\n        rpt_community_stats_daily p\n    group by 1\n\n),\n\nfinal as (\n\n    select\n        p.time_period\n        ,p.page_views\n        ,p.new_page_views\n        ,p.unique_visitors\n        ,p.unique_pages\n        ,avg(p.page_views) over (order by p.time_period rows between (${moving_average_periods}-1) preceding and current row) as moving_average\n    from\n        page_views p\n\n)\n\nselect *\nfrom final\nwhere \n    $__timeFilter(time_period)\n    and time_period between '2023-04-07' and '2024-03-28'\norder by 1\n"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 26 },
   "options": {
    "content": "<p \n  style=\"font-size:350%;text-align:center; font-weight:normal;color:#cBD0200;>\"\n>\nSources of Page View Growth\n</p>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 29 },
   "options": {
    "content": "<p \n  style=\"font-size:150%;text-align:center; font-weight:normal;color:#cBD0200;>\"\n>\n💡 Key Question 💡 - Generally, are there any clear <span style=\"color: rgb(87, 148, 242)\">primary growth drivers</span> - new vs. existing pages? Top 10 vs. all other pages?\n</p>\n"
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select \n    'new_vs_existing' as new_vs_existing\n    ,'top_100_vs_others' as top_100_vs_others\n    ,'category' as category\n    ,'sub_category' as sub_category"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Monthly Community Page Views: ${monthly_group_by}",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "with\n\nmonthly_page_data_sub1 as (\n\n    select\n        date_trunc('month', p.received_date) as received_month\n        ,p.page_path\n        ,case\n            when max(p.is_page_first_day) then 'New'\n            else 'Existing'\n        end as new_vs_existing\n        ,sum(p.page_views) as page_views\n    from\n        rpt_community_page_stats_daily p\n    group by 1,2\n\n),\n\nmonthly_page_data_sub2 as (\n\n    select\n        p.*\n        ,row_number() over (partition by p.received_month order by p.page_views desc) as page_view_rank\n    from\n        monthly_page_data_sub1 p\n\n),\n\nmonthly_page_data as (\n\n    select\n        p.*\n        ,case\n            when p.page_view_rank <= 100 then 'Top 100'\n            else 'Other'\n        end as top_100_vs_others\n    from\n        monthly_page_data_sub2 p\n\n),\n\nfinal as (\n\n    select\n        p.received_month as time_period\n        ,p.${monthly_group_by} as group_value\n        ,sum(p.page_views) as page_views\n    from\n        monthly_page_data p\n    group by 1,2\n\n)\n\nselect *\nfrom final\nwhere\n    $__timeFilter(time_period)\n    and time_period between '2023-04-07' and '2024-03-28'\norder by 1\n"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 49 },
   "options": {
    "content": "<p \n  style=\"font-size:350%;text-align:center; font-weight:normal;color:#cBD0200;>\"\n>\nIndividual Community Page Details\n</p>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 52 },
   "options": {
    "content": "<p \n  style=\"font-size:150%;text-align:center; font-weight:normal;color:#cBD0200;>\"\n>\n💡 Key Question 💡 - Have there been any individual pages that have been a <span style=\"color: rgb(163, 82, 204)\">primary contributor to growth</span>?\n</p>\n"
   }
  },
  {
   "title": "Page Views by ${time_period}: ${community_page_title}",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "with\n\npage_views as (\n\n    select\n        date_trunc('${time_period}', p.received_date) as time_period\n        ,sum(page_views) as page_views\n    from\n        rpt_community_page_stats_daily p\n    where\n        p.page_title = cast(${community_page_title:sqlstring} as String)\n    group by 1\n\n),\n\nfinal as (\n\n    select\n        p.time_period\n        ,p.page_views\n        ,avg(p.page_views) over (order by p.time_period rows between (${moving_average_periods}-1) preceding and current row) as moving_average\n    from\n        page_views p\n\n)\n\nselect *\nfrom final\nwhere\n    $__timeFilter(time_period)\n    and time_period between '2023-04-07' and '2024-03-28'\norder by 1\n"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "Individual Community Pages (with a total >100 page views per day)",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "with\n\nfinal as (\n\n    select\n        p.page_title\n        ,p.page_path\n        ,case\n            when max(p.is_page_first_day) then 'New'\n            else 'Existing'\n        end as new_vs_existing\n        ,sum(page_views) as page_views\n        ,sum(unique_visitors) as unique_visitors\n    from\n        rpt_community_page_stats_daily p\n    where\n        $__timeFilter(received_date)\n    group by 1,2\n\n)\n\nselect *\nfrom final\nwhere page_views > 10\norder by 4 desc\n"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 78 }, "options": { "content": "---" } },
  { "title": "Appendix", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 } },
  { "title": "Related Dashboards", "type": "dashlist", "gridPos": { "h": 11, "w": 24, "x": 0, "y": 81 } }
 ]
}