version: '3.0'

services:
#  postgres_db:
#    image: postgres:15
#    restart: always
#    ports:
#      - 5432:5432
#    volumes:
#      - ./postgres/community_data/:/usr/share/community_data/
#      - ./postgres/sql/create_example_tables.sql:/docker-entrypoint-initdb.d/create_example_tables.sql
#      # - ./postgres/sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
#    environment:
#      POSTGRES_DB: community_db
#      POSTGRES_USER: community_user
#      POSTGRES_PASSWORD: community_pwd

  grafana:
    container_name: 'grafanacon2024_bi_dashboards'
    build:
      context: ./grafana/.config
    ports:
      - 3000:3000/tcp
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/config/grafana.ini:/etc/grafana/grafana.ini
    environment:
      GF_INSTALL_PLUGINS: grafana-clickhouse-datasource
    networks:
      - grafana

  clickhouse:
    image: 'clickhouse/clickhouse-server:23.3'
    container_name: 'grafana-clickhouse-server'
    ports:
      - '8123:8123'
      - '9000:9000'
      - '5432:5432'
      - '3306:3306'
    volumes:
      - ./clickhouse/data:/var/lib/clickhouse
      - ./clickhouse/community_data:/home/community_data
      - ./clickhouse/config.d/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ./clickhouse/users.d/users.xml:/etc/clickhouse-server/users.d/users.xml
      - ./clickhouse/init_scripts:/docker-entrypoint-initdb.d
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - grafana

networks:
  grafana:
