version: '3.0'

services:
  grafana:
    container_name: 'grafanacon2024_bi_dashboards'
    build:
      context: ./grafana/.config
    ports:
      - 3000:3000/tcp
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/config/grafana.ini:/etc/grafana/grafana.ini
    environment:
      GF_INSTALL_PLUGINS: grafana-clickhouse-datasource
    networks:
      - grafana

  clickhouse:
    image: 'clickhouse/clickhouse-server:24.1'
    container_name: 'grafana-clickhouse-server'
    ports:
      - '8123:8123'
      - '9000:9000'
      - '5432:5432'
      - '3306:3306'
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - grafana

networks:
  grafana:
